
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TwitterService", targetNamespace = "http://veebiteenused.ttu.ee", wsdlLocation = "file:/C:/Users/ANDREAS/iti0050/hw_api_soap/src/soap/twitter1.wsdl")
public class TwitterService
    extends Service
{

    private final static URL TWITTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TWITTERSERVICE_EXCEPTION;
    private final static QName TWITTERSERVICE_QNAME = new QName("http://veebiteenused.ttu.ee", "TwitterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/ANDREAS/iti0050/hw_api_soap/src/soap/twitter1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TWITTERSERVICE_WSDL_LOCATION = url;
        TWITTERSERVICE_EXCEPTION = e;
    }

    public TwitterService() {
        super(__getWsdlLocation(), TWITTERSERVICE_QNAME);
    }

    public TwitterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TWITTERSERVICE_QNAME, features);
    }

    public TwitterService(URL wsdlLocation) {
        super(wsdlLocation, TWITTERSERVICE_QNAME);
    }

    public TwitterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TWITTERSERVICE_QNAME, features);
    }

    public TwitterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TwitterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TwitterPortType
     */
    @WebEndpoint(name = "TwitterPort")
    public TwitterPortType getTwitterPort() {
        return super.getPort(new QName("http://veebiteenused.ttu.ee", "TwitterPort"), TwitterPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TwitterPortType
     */
    @WebEndpoint(name = "TwitterPort")
    public TwitterPortType getTwitterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://veebiteenused.ttu.ee", "TwitterPort"), TwitterPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TWITTERSERVICE_EXCEPTION!= null) {
            throw TWITTERSERVICE_EXCEPTION;
        }
        return TWITTERSERVICE_WSDL_LOCATION;
    }

}
